### ISSUE TITLE
how to decode 4 digit buffers.

### ISSUE THREAD

**Issue by sidshash** [kawanet/msgpack-lite#108]
i can decode buffer starting with '0x' like 0xA3, 0x64 0x22 etc. But how can i decode buffer like 3c01, 4eab, a474 which are not starting with '0x'. when i try to run msgpack.decode(Buffer([3c01, 4eab, a474])). It gives syntax error.

**Comment by kevinramharak** [comment]
Please take a look at this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Numbers_and_dates#Hexadecimal_numbers. A number in javascript can be written in a few different ways. `0xA` is just a different notation (hexadecimal) of `10` (decimal). I suggest you learn the fundamentals of Javascript if this is confusing you.
