### ISSUE TITLE
Cursor streaming buffer or abstract class

### ISSUE THREAD

**Issue by kawanet** [kawanet/msgpack-lite#11]
This package (will) support the following usages.

 | usage | input | output
----|----|----|----
1 | var buf = msgpack.encode(obj)   |  1 object | 1 msgpack
2 | msgpack.Encoder().on("data", onData).encode(obj)  | objects | msgpacks
3 | msgpack.createEncodeStream().pipe(stream)  |  objects |  streaming
4 | var obj = msgpack.decode(buf) | 1 msgpack | 1 object
5 | msgpack.Decoder().on("data", onData).decode(buf) | msgpacks | objects
6 | stream.pipe(msgpack.createDecodeStream()) | streaming | objects

it seems to need a kind of Encoder abstract class to implement concat option described on issue #5 without any performance penalties.

After the refactoring works done recently, both `Encoder` and `Decoder` class are smaller than before. However, it seems EventEmitter-style on usage 2 and 5 looks better to be separated with other usages.

`Encoder` and `Decoder` classes could be separated to an abstract class for all usages above and a subclass supporting EventEmitter.

**Comment by kawanet** [comment]
### Plan A - Abstract Class

Implementing abstract class and sub classes intended to 6 usages above.

**Comment by kawanet** [comment]
### Plan B - Cursor Streaming Buffer Class

Implementing a commonly available cursor-base buffer class. 

write-core.js and read-core.js provide lower level functionality after the refactoring done recently.

```js
require("./write-core").encode(encoder, value);
require("./read-core").decode(decoder, value)
```

`encode()` requests an `Encoder` object which has the following properties/methods.

- buffer
- offset
- reserve()
- send() 

`decode()` requests a `Decoder` object which has the following properties/methods.

- buffer
- offset
- bufferLength *(alternative available: decoder.buffer.length)*

Both could be changed to a simplified buffer object which has a cursor.

**Comment by kawanet** [comment]
### Proposal 1 for plan B

writng usage:

```js
var buf = new CursorBuffer();
buf.reserve(1); // ensure range of buffer writable
buf.buffer[buf.offset++] = val; // write a byte
buf.send(buffer); // write another buffer at the cursor point
```

reading usage:

```js
var buf = new CursorBuffer();
buf.append(buffer); // append another buffer at the end of the current buffer
buf.request(1); // ensure range of buffer readdable
var val = buf.buffer[buf.offset]; // read a byte
```

**Comment by fearthecowboy** [comment]
Sweet mercy you work fast; I've been busy on other stuff this week, now I have a ton of reading to do!

**Comment by kawanet** [comment]
Codes are simplified.

- All encoding interfaces use `encode-buffer.js` buffer and `write-core.js` encoder.
- All decoding interfaces use `decode-buffer.js` buffer and `read-core.js` decoder.

> perhaps there is a means that we can completely abstract out the encode and decode functionality away from how/where/when buffers and space are allocated.

I'm not sure that above is similar to what you mentioned however. This hints me anyway.
