### ISSUE TITLE
Move other msgpack libs into devDependencies

### ISSUE THREAD

**Issue by mcollina** [kawanet/msgpack-lite#17]
I guess those are needed only for running the benchmarks, so you can reduce the downloads when installing this library

**Comment by kawanet** [comment]
Oops! You're right that they are only needed for the benchmarks and compatibility tests. At commit 7fc8247 , I've just moved them **from devDependencies to optionalDependencies**, as one of them fails to install with some node.js versions.

OptionalDevDependencies parameter should be the best for this case, however.

I'll fix it soon, anyway. Thank you for the report.
