### ISSUE TITLE
  mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create1 msgpack.min.js:1:23202

### ISSUE THREAD

**Issue by titoBouzout** [kawanet/msgpack-lite#18]
Hi there Firefox is reporting it,can we avoid it?

**Comment by mtth** [comment]
This is likely caused by browserify's `Buffer` implementation (see [here](https://github.com/feross/buffer#how-does-it-work)).

AFAIK, the simplest way to get around it is to set `window.TYPED_ARRAY_SUPPORT` to `false` before you include this script.

**Comment by titoBouzout** [comment]
But removing typed arrays support could make it even slower. To clarify, I don't mind what the message, what I want is to execute this library in the most performant way possible.

**Comment by mtth** [comment]
It depends on the browser. In Firefox disabling typed array support will actually give you a significant performance boost. In Chrome it'll be marginally slower (more if you `slice` a lot).

**Comment by kawanet** [comment]
Firefox looks firing the warning at the following code:

```js
if (Buffer.TYPED_ARRAY_SUPPORT) {
  Buffer.prototype.__proto__ = Uint8Array.prototype
  Buffer.__proto__ = Uint8Array
```

It'd depends on Buffer implementation.
https://github.com/feross/buffer
