### ISSUE TITLE
Use of Buffer is killing performance.

### ISSUE THREAD

**Issue by fearthecowboy** [kawanet/msgpack-lite#2]
Howdy!

I'm using *msgpack-lite* in a *very* high performance situation, and I've discovered a bit about some of the way that you're doing some stuff that's robbing you of performance greatly.

It turns out that *any* use of `new Buffer(...)` or `Buffer.concat()`is terrible for performance.  

Reallocating a buffer during `flush()` pretty much guarantees that you're losing some very valuable performance, and returning objects from `encode()` kills it too.

I started tweaking msgpack-lite and in my case exposed the Encoder type out to the consumer, and have it keep it's internal buffer, and only reallocate if the size of the current `encode()` is exceeding it.

I use it like this now:

``` javascript
    var msgpack = require("msgpack-lite");
    // ....

    var enc = new Encoder();
    // ... 

    /// in a tight loop somewhere
    // msg is some object from somewhere
    var buf = enc.encode( msg ); 

    // buf is .slice() 'd  from the internal buffer in the object 
    // slice() is a cheap operation, since it doesn't actually allocate more data
    // it just creates a view

   // at that point, you can do what you want with it...
   somestream.write( buf );

```

Using *msgpack-lite* in this way, I'm able to encode and process around **200,000 messages per second** in on a single core in a VM.

I'm working on a pull request for the changes, once I clean up the hacking mess I did :)

Incidentally, in `buffer-lite.js` it mentions:
```
    // new Buffer(string, "utf-8") is SLOWER then below
```

I imagine that Buffer allocation speed is what's really killing that. If you pre-allocate and re-use the buffer, and just use `buffer.write(string, 'utf-8') ` it appears to be much better.

**Comment by kawanet** [comment]
Yay! It sounds sweet. You're right that an allocating a Buffer is expensive.
Encoder's internal buffer is the key of the performance.
I'm looking forward to seeing the PR.

It's currently undocumented because the Encoder class is not public at the current version, Encoder class is designed for streaming encoding.

```js
var Encoder = require("msgpack-lite/lib/encoder");
var enc = new Encoder(somestream);
enc.encode( msg1 ); 
enc.encode( msg2 ); 
enc.encode( msg3 ); 
```

This may give a bit less overhead.

---

Let me see. Hmm. I may understand what you mean.

```js
Encoder.prototype.encode = function(chunk, encoding, callback) {
  if (!this.buffer) this.flush(); // <---- you want to reuse a previous buffer if possible
  encode(this, chunk);
  this.flush(); // <---- you don't want this flushing
  if (callback) callback();
};
```

It creates and flushes the internal buffer for each of every input.

----

The following steps work for your case?

1. remove the second `this.flush();` on encode() method.
2. export Encoder class and allow applications to handle flush() by themselves.

```js
var Encoder = require("msgpack-lite").Encoder;
var enc = new Encoder(somestream);
enc.encode( msg1 ); 
enc.encode( msg2 ); 
enc.encode( msg3 ); 
enc.flush(); // flush encoder's internal buffer
```

The only reason why the Encoder class is currently private and NOT exported yet is the constructor's argument signature is not finally decided at this moment. Only one argument of output stream may be enough however.

**Comment by kawanet** [comment]
Another solution:

1. remove the second `this.flush();` on `Encoder.prototype.encode` method.
2. implements `EncodeStream.prototype._flush` method.

This may be more easy for developers to understand the streaming usage.

```js
var msgpack = require("msgpack-lite");
var enc = msgpack.createEncodeStream();
enc.pipe( somestream );
enc.write( msg1 ); 
enc.write( msg2 ); 
enc.write( msg3 ); 
enc.flush(); // flush encoder's internal buffer
```

See https://nodejs.org/api/stream.html#stream_transform_flush_callback

**Comment by fearthecowboy** [comment]
I'm just working thru a couple more points of optimization; I should have a PR soon (at least so you can see where I'm going...). I'm to the point where my changes don't break any tests now :)

I've been using both the `createEncodeStream()` style and the `encode(...) ` style.

I've gotten a bit more deep than just simply optimizing the use of `flush()`. I've got it exponentially resizing the buffer if a given encode requires more space.

I'm aggressively trying to make sure that for a given operation, that I can absolutely minimize the number of buffers created (and `Buffer.concat`, and any other perf-killing functions).

I've essentially changed the behavior of `flush()` to more of a 'reserveSpace()' call. 

A few more minutes, and I should have something...

**Comment by fearthecowboy** [comment]
I've sent the PR; we can discuss it before you accept it if you want.

I haven't really touched the decoder yet to do a similar thing, I'll try to do that next week.

The other thing I thought I'd mention is that the `Transform` streaming stuff works ok, except that in general the `.pipe`  model of NodeJS streams is actually terrible perf-wise.

I've discovered that anything that uses '.push()' or causes a new `Buffer` allocation ends up being generally terrible for maximum performance.

I've been experimenting with an `EventEmitter` model for processing messages, and so far I can say that it's perf is quite significantly better than using `.pipe()` on streams.

**Comment by kawanet** [comment]
Yay! Thank you for the PR #3 

I'll run it to get benchmarks later as I don't have time today. Before running it, I've read diff of your code. As you can see at the lib/bench.js, I've been focusing primary on perf on individual encoding but not streaming encoding. I'm happy to see getting better streaming perf with those changes.

It looks that you're focusing on large number of small messages streaming such like fluentd logging. Could you let me know a sample message you're working on? Let's have a benchmark with your use case then.

----

(1) `.reserve()` changes look good and clear about what it does.

```diff
-  var end = this.offset + buffer.length;
-  if (end >= BUFFER_LENGTH) {
-    this.flush();
+  this.reserve( buffer.length );
```

At the early stage of developing the module, I've removed method invocations to get better performance.
It means `(end >= BUFFER_LENGTH)` gives less `flush()` method invocations. Recently it has got significant perfomance improvements after removing some Buffer allocations. I'm not sure that invoking `reserve()` method every time may decrease perf or not. I guess it may give a tiny impact, compared to Buffer allocations matter, with the current code base. I'll check it.

If it gives a ignorable impact, I'd love to merge it.

----

(2) Resizing double and copying buffer may do similar thing than `Buffer.concat()`. I'm curious that this makes perf better?

```diff
+    // resize it to 2x current length (or at least length!)
+    var newbuffer = new Buffer( Math.max(this.buffer.length * 2, length+this.offset ) );
+    this.buffer.copy( newbuffer, 0, 0, this.offset );
```

> I've discovered that anything that uses `.push()` or causes a new `Buffer` allocation ends up being generally terrible for maximum performance.

Interesting. You mean (a) "*`push()` and `Buffer.concat()`*" way is slower than (b) "*resizing double and copying buffer*" way? It's worth to try.

----

(3) `Encoder.prototype.write` has a special purpose compared to the other methods such as `write1`.

It calls `push()` for two ways: (A) "*pushing to internal array of buffers*" for individual encoding, (B) "*pushing directly to output stream*" for streaming encoding. It is a hack to call `Array.prototype.push` and `WritableStream.prototype.push` by a same method!

The current `write` method does `flush` and `push` when the given chunk is bigger than the current buffer. It is intended to writing a huge Uint8Array or Buffer **directly** to the output stream without memory copying. I mean it'd be better when writing several mega bytes of binary files such as JPEG, PNG, SQLite, etc. as I'd like to use the msgpack as a data storage in my use case.

I guess `Encoder.prototype.write` should keep the feature that could do no memcpy. I guess "*resizing double and copying buffer*" would get better perf for smaller messages, as your PR does. On the other hand, "*writing directly to output stream*" would get better for larger messages. I'll check it later anyway.

----

> I've been experimenting with an `EventEmitter` model for processing messages, and so far I can say that it's perf is quite significantly better than using `.pipe()` on streams.

Interesting. You mean Nodejs's stream is slow? It's flexible however.

**Comment by kawanet** [comment]
It looks 15%-20% faster than the original according to the new benchmark at a glance.

Original 1ffd37f              |   op   |  ms  |  op/s 
---------------------------------------- | -----: | ---: | -----:
stream.write(msgpack.encode(obj));       | 100000 | 1685 |  59347
msgpack.createEncodeStream().write(obj); | 100000 | 1303 |  76745

PR #3 d4cb247          |   op   |  ms  |  op/s 
---------------------------------------- | -----: | ---: | -----:
stream.write(msgpack.encode(obj));       | 100000 | 1411 |  70871
msgpack.createEncodeStream().write(obj); | 100000 | 1027 |  97370

**Comment by fearthecowboy** [comment]
>> It looks that you're focusing on large number of small messages streaming such like fluentd logging
uh, fluentd? who said I was doing fluentd? ... Yeah, that's what I'm doing.  :)

>> I've removed method invocations to get better performance.
Given the way that JavaScript JITing works, there's no performance benefit by working like that; consolidating that makes sure that I leave less bugs behind :D 
 
>> Interesting. You mean (a) "push() and Buffer.concat()" way is slower than (b) "resizing double and copying buffer" way? It's worth to try.

Resizing the buffer to double the size is designed to keep the number of reallocations down. You won't see perf increases in your current tests because you're not re-using the Encoder object. In the case where the Encoder is preserved, you'll find that the buffer will quickly find the right size given the typical usage.

>> It calls push() for two ways: (A) "pushing to internal array of buffers" for individual encoding, (B) "pushing directly to output stream" for streaming encoding. It is a hack to call Array.prototype.push and WritableStream.prototype.push by a same method name!

Yeah, I saw that; the trouble is that both those methods are terrible for performance. 

>> Interesting. You mean Nodejs's stream is slow? It's flexible however.

Which brings me to my other assertion: Node's Streams impementation (ie, Transform, Writable, Readable) are a nice, flexible interface, it's just really crappy for performance. 

I rewrote my implementation to use an EventEmitter-style model, and I was seeing **far** better results. I even went so far as to write a fairly smart BufferedTransform just to make sure that it wasn't small-message stream fatigue, and it turns out that the general stream implementation is just not quite as good for performance as I needed.

>> It looks 15%-20% faster than the original according to the new benchmark at a glance
It gets an order of magnitude faster when you re-use the Encoder object :) 

>> It is intended to writing a huge Uint8Array or Buffer directly to the output stream without memory copying. 
I was thinking about that. While that seems like it should be important for performance, the extra usage of memory space appears to be better than using the stream directly. Perhaps I'll look into that a bit more.

**Comment by kawanet** [comment]
Thank you and I've merged the PR and updated something on it after that. I'm happy to discuss about the performance growing with you.

- Make test passed on node v0.10 and 0.12 and io.js 3.1
- Streaming benchmark added.
- reserve() method are good to understand. Merged.
- Streaming usage of _transform() and _flush() are moved to *Stream classes.
- Encoder class's argument initialSize needs redesigning with the other options such as ExtBuffer customizing. Reverted at this build.

Try lib/benchmark-stream.js. You're right that reusing Encoder object is twice faster than EncodeStream surprisingly.

**Comment by kawanet** [comment]
Encoder class constructor accepts one argument of `output` which could be one of an `Array` instance and `ReadStream` (such as Transform) as both accepts the `push` method  as I mentioned.

I'd like to design the API to send a series of multiple messages to somewhere (like fluentd, for instance) by reusing Encoder object. `destination` is a writable TCP connection to fluentd server or something like that.

(a) `msgpack.createEncodeStream().pipe(destination)` is already available. But it may slow compared to the other ways below

(b) `msgpack.Encoder(destination)` is fast, according to the new benchmark. However it sends messages via `push` method instead of `write` method. I prefer to keeping individual encoding performance as well as streaming performance. `push` is the key to the individual encoding usage, in my opinion. (individual usage means `encode.js`. streaming usage means `encode-stream.js`)

(c) `msgpack.Encoder({stream: destination})`

(d) `msgpack.Encoder().pipe(destination)` - This looks good. However, in this design, developers may want some more methods implemented, such as end() or on("data") things as Net/Stream interface have them.

(e) any good ideas?

**Comment by fearthecowboy** [comment]
I'll see if I can get some time in the next day or so to take a look at the newest version and see how it plays with my code :)

Another day or two, and I should have my `EventEmitter`-style usage cleaned up, and maybe we can put that in there beside the `Transform` implementation to give developers an couple easy means for tying it to streams. 

I've switched over to working with the `Decode` side of my app today. We'll see what happens there :)

**Comment by fearthecowboy** [comment]
Ah... the changes you made killed my performance again.

I see that the flush needed to support the way you have the `Transform` working, but now you're just killing the buffer every time it flushes, which requires it to realloc it again.

**Comment by kawanet** [comment]
I've applied a patch d00df50 for "resize internal buffer to 2x length" technique. I still think that it needs an internal buffer size limitation such as MAX_BUFFER_SIZE which is 64KB at the patch.

> I see that the flush needed to support the way you have the Transform working, but now you're just killing the buffer every time it flushes, which requires it to realloc it again.

It flushes and reallocs only when needed at the current code.

**Comment by fearthecowboy** [comment]
I was playing with the code again last night, running the benchmarks.

I'm not sure why, but from run-to-run, those benchmarks have a lot of variance.  I was trying to do some comparison runs on changes I had made, and it's really hard to get solid numbers that don't vary by upwards of 10% or more.

I still gotta play around some more...

**Comment by fearthecowboy** [comment]
I've been doing some more thinking; perhaps there is a means that we can completely abstract out the `encode` and `decode` functionality away from how/where/when buffers and space are allocated.

The trick of course, is to ensure that it's done in a way that doesn't impact performance in any scenario.

Done correctly, this puts the responsibility of _how_ a developer wants to manage their bytes/buffers/stream in their hands without making judgements on the parser/encoder.

Of course, that's a fairly low-level concept, and you'd definitely want to expose the convenient interfaces on top of that (streaming `Transform`, `encode()`, etc) so _most_ developers can find an acceptable out-of-the-box solution.

The trick, is to find the time to make a prototype of this so we can move ahead :)

**Comment by kawanet** [comment]
> I'm not sure why, but from run-to-run, those benchmarks have a lot of variance.

100,000 operations were not enough to run benchmark. I've increased it to 1,000,000.
It'd gives more accuracy such as few percent difference.
Did you pull https://github.com/kawanet/msgpack-lite/commit/410d1d9 ?

Benchmark-stream.js runs the benchmarks multiple times and shows the fastest result.
Other processes on the same machine may effect the benchmark process.

```sh
nice -n +10 lib/benchmark-stream.js 5
```

This may give the process priority.

**Comment by kawanet** [comment]
> The current write method does flush and push when the given chunk is bigger than the current buffer. It is intended to writing a huge Uint8Array or Buffer directly to the output stream without memory copying. I mean it'd be better when writing several mega bytes of binary files such as JPEG, PNG, SQLite, etc.

I finally found a specific usage which requests NOT to divide an encoded message into multiple chunks. WebSocket is that. On the WebSocket, a single chunk should represents a single object. I've added another issue #5 then.

It seems that some topics are discussed on this issue. I've added some separated issues. Please add another issue if you have. So I'm closing this issue now.

Thank you for giving me many hints here, anyway!
