### ISSUE TITLE
Example from README.md is not working.

### ISSUE THREAD

**Issue by Amberlamps** [kawanet/msgpack-lite#20]
I tried:

```
var fs = require("fs");
var msgpack = require("msgpack-lite");

var writeStream = fs.createWriteStream("test.msp");
var encodeStream = msgpack.createEncodeStream();
encodeStream.pipe(writeStream);

// send multiple objects to stream
encodeStream.write({foo: "bar"});
encodeStream.write({baz: "qux"});
```

I am on Windows 8.1 and tried Node versions 0.12.2, 4.2.0, 4.2.2 and 5.0.0.
The script always creates an empty "test.msp". It seems like https://github.com/kawanet/msgpack-lite/blob/master/lib/encode-stream.js#L26 is never called.

**Comment by mtth** [comment]
@Amberlamps - you have to [`end`](https://nodejs.org/api/stream.html#stream_writable_end_chunk_encoding_callback) the writable stream to flush everything:

```javascript
encodeStream.write({foo: "bar"});
encodeStream.write({baz: "qux"});
encodeStream.end(); // Call this once you're done writing to the stream.
```

**Comment by kawanet** [comment]
Thanks both!
