### ISSUE TITLE
Document which version of msgpack is supported

### ISSUE THREAD

**Issue by hungryblank** [kawanet/msgpack-lite#21]
I could not find documented anywhere which version of the msgpack spec this library supports

**Comment by kawanet** [comment]
This supports the current version of msgpack spec documented at msgpack.org website.
I guess it's v5. The official document looks never have mentioned that it is v5, however.

**Comment by kawanet** [comment]
According to https://github.com/msgpack/msgpack/issues/195 , there are no official version number for the current msgpack specification, unfortunately. The `msgpack-lite` library support both of the [current version](https://github.com/msgpack/msgpack/blob/master/spec.md) and the [old version](https://github.com/msgpack/msgpack/blob/master/spec-old.md) of specs.
