### ISSUE TITLE
Publish 0.1.16 to NPM

### ISSUE THREAD

**Issue by JoshuaWise** [kawanet/msgpack-lite#26]
Just a reminder to publish the most recent version of msgpack-lite to [npm](https://www.npmjs.com/), so its dependents can be updated.

**Comment by kawanet** [comment]
Now published and you are listed on [package.json](https://github.com/kawanet/msgpack-lite/blob/master/package.json). Thanks!

**Comment by JoshuaWise** [comment]
Great, thanks!
