### ISSUE TITLE
64bit int decode error: Object doesn't support property or method 'readInt32BE'

### ISSUE THREAD

**Issue by pharring** [kawanet/msgpack-lite#27]
```JavaScript
msgpack.decode([129, 161, 120, 211, 0, 0, 0, 0, 0, 0, 0, 0]);
```

Result: Object doesn't support property or method `readInt32BE'

I see #1 about true 64-bit integer support, but this is more of a decoder error. I can work around this in my own code (by adding the missing methods, readInt32BE and readUInt32BE). In my case, I'm dealing with data downloaded from an ASP.Net server running a C# implementation of the msgpack protocol where 64-bit integers (long/ulong) are supported natively.

**Comment by kawanet** [comment]
msgpack.decode() requests `Buffer` instance instead of `Array` instance.

```js
msgpack.decode(Buffer([129, 161, 120, 211, 0, 0, 0, 0, 0, 0, 0, 0]));
```

This would work at node.js. See #28.

**Comment by kawanet** [comment]
Now `msgpack.decode()` accepts Array instance!

```js
msgpack.decode([129, 161, 120, 211, 0, 0, 0, 0, 0, 0, 0, 0]); // => {x: 0}
```
