### ISSUE TITLE
decode Array and Uint8Array

### ISSUE THREAD

**Issue by kawanet** [kawanet/msgpack-lite#28]
The current version of msgpack.decode() accepts only `Buffer` instance as node.js supports `Buffer`. On browser environment, it'd be useful when msgpack.decode() accepts plain old `Array` and `Uint8Array` as well as `Buffer`.

See also:

- msgpack.decode(new Uint8Array(data)) leads to "Uncaught TypeError: this.readUInt32BE is not a function" #16
- 64bit int decode error: Object doesn't support property or method 'readInt32BE' #27

**Comment by kawanet** [comment]
I found that [README](https://github.com/kawanet/msgpack-lite#browser-build) has mentioned Uint8Array for browser usage. I've added Array and Uint8Array support, then.

```js
// decode() also accepts Array instance
msgpack.decode([0x81, 0xA3, 0x66, 0x6F, 0x6F, 0xA3, 0x62, 0x61, 0x72]);

// decode() accepts raw Uint8Array instance as well
msgpack.decode(new Uint8Array([0x81, 0xA3, 0x66, 0x6F, 0x6F, 0xA3, 0x62, 0x61, 0x72]));
```

**Comment by pharring** [comment]
Excellent! Thanks for the fast turn-around.
