### ISSUE TITLE
add msgpack.isSupported for the browser version

### ISSUE THREAD

**Issue by mozi** [kawanet/msgpack-lite#30]

**Comment by kawanet** [comment]
Is it a method?

```js
if (msgpack.isSupported("feature", "version")) { ... }
```

Could you let me know a use case?

**Comment by mozi** [comment]
It could be a method or it could be a property.
The use case is simply the library doesn't work on Android 6 built-in browser, and noticed its not supported on the homepage as well, so it would be helpful to have a method available on the browser version to detect if it can work with the browser the user using.

**Comment by kawanet** [comment]
@mozi It looks it works on Android 6.0 built-in browser, by the way.
Did you see any error messages?

**Comment by kawanet** [comment]
It passes all tests on Android 6.0 built-in browser.

```sh
make test-browser-local
```

Try http://192.168.xxx.xxx:4000/__zuul then.

It looks that SauceLab does not support 6.0 still however.

**Comment by mozi** [comment]
Thanks, I can confirm that it is indeed working on Android 6 native browser.
