### ISSUE TITLE
reading from a messagepack stream

### ISSUE THREAD

**Issue by tony-garcia** [kawanet/msgpack-lite#31]
Hello,
I'm trying to use msgpack-lite to read from a messagepack stream and I'm using the code straight out of the examples, but I'm getting 'msgpack.createDecodeStream is not a function'. Did the API change? What is the correct way to read from a messagpack stream? Thanks.

**Comment by kawanet** [comment]
Let me know you're running it on browser? or on node.js?

msgpack.createDecodeStream is exported only on node.js because it depends on Stream module.
It seems that there are Stream-shim for browsers, by the way. 
This may allow browsers to run createDecodeStream with small code changes.

https://www.npmjs.com/package/stream-browserify

**Comment by tony-garcia** [comment]
Well, I'm running it in a nodejs context in an electron app. So as such I have access to the stream module (so I should be able to use createDecodeStream). But I don't know if you take into account that this package could be used in an electron app.

**Comment by tony-garcia** [comment]
Hmm... so it seems like this is an issue that is related to [this](https://github.com/atom/electron/issues/1574). In my case it unnecessarily handicaps the package in an electron app because I would be able to use the stream methods. I'll look into the stream-browserify thing you pointed me to and let you know if I need any help.

**Comment by kawanet** [comment]
Try a *work-around* below:

```js
var msgpack = require("msgpack");

msgpack.createDecodeStream = require("msgpack-lite/lib/decode-stream").createDecodeStream; // add this
```

**Comment by tony-garcia** [comment]
Thanks for the tip. Still having issues, though, so I'm not sure if I'm doing things right. Basically my app is receiving messages from a rabbitmq broker on an embedded system where messages are being written to a messagepack stream using C++ before being published. I happen to know that 4 values are being written to the stream. When I receive the message, I'm trying to use msgpack-lite to unpack and read the values. If I use just a plain msgpack.decode() on the message contents, it only gives me the first value, so I'm assuming that I have to convert the received message on my end into a stream and then pipe it into a decodeStream. That's where I'm stuck. I can write a python script to read the contents by using [io.BytesIO](https://docs.python.org/2/library/io.html#io.BytesIO) to convert the received message to a stream. However I can't seem to do the same using node. The received message shows up as a Uint8Array in the electron dev console and I've tried [this](http://stackoverflow.com/questions/32192287/converting-uint8array-into-stream-with-node-js) and [this](http://stackoverflow.com/questions/16038705/how-to-wrap-a-buffer-as-a-stream2-readable-stream) to try to convert that into a stream but no luck. Probably approaching it the wrong way, though. Any tips would be greatly appreciated.

**Comment by tony-garcia** [comment]
Never mind. Got it working with your workaround. Basically, what I was getting back (that was showing up as a Uint8array in my console) was a Buffer and this is what I did:

`
stream = require('stream');

var bufferStream = new stream.PassThrough();
bufferStream.end(msg.content);   // msg is the message that's coming from the broker. Convert content to a stream
var decodeStream = msgpack.createDecodeStream();
bufferStream.pipe(decodeStream).on('data', chunk => {
    // read values from message and do whatever
});
`

Thanks a lot for the workaround.

**Comment by kawanet** [comment]
`msgpack.decode()` method only decodes a single msgpack value because it has a synchronous interface.

msgpack-lite has yet another public (tested but not documented) class `msppack.Decoder` which has an async event model interface and can decode a sequence of multiple msgpack values.

```js
var msgpack = require("msgpack-lite");
var decoder = new msgpack.Decoder();
decoder.on("data", chunk => { ... });
decoder.decode(first_content); // of Buffer, Uint8Array or Array
decoder.decode(second_content); // if you have
decoder.decode(third_content);
decoder.end(last_content);
```

Stream interface `msgpack.createDecodeStream`, as you used, should also work well for those use cases however.

**Comment by tony-garcia** [comment]
Interesting. Where/how would I pass in my message to stream-decode using the Decoder class? In the constructor?

**Comment by kawanet** [comment]
```js
var decoder = new msgpack.Decoder();
decoder.on("data", chunk => {
    // read values from message and do whatever
});
decoder.decode(msg.content);
decoder.end();
```

OR 

```js
var decoder = new msgpack.Decoder();
decoder.on("data", chunk => {
    // read values from message and do whatever
});
decoder.end(msg.content); // end immediately
```

**Comment by tony-garcia** [comment]
OK -- got it. Thanks again!
