### ISSUE TITLE
Unpack c# msgpack

### ISSUE THREAD

**Issue by Almis90** [kawanet/msgpack-lite#32]
I using https://github.com/msgpack/msgpack-cli and here are my classes

```
[DataContract]
public class Client
{
    [DataMember(Order = 0)]
    public int Id { get; set; }
    [DataMember(Order = 1)]
    public Information Information { get; set; }
}

[DataContract]
public class Information
{
    [DataMember(Order = 0)]
    public string Name { get; set; }
}
```

When I unpack it from server side I get

`[1, ['John']]`

The data is correct but it's not an object. I understand the reason but is there any way to convert it to my model?

**Comment by kawanet** [comment]
msgpack itself doesn't have a kind of object mapping feature by nature.

I have no idea whether the C# binding might have it however.

Why don't you ask it at https://github.com/msgpack/msgpack-cli/issues ?

**Comment by Almis90** [comment]
When I pack the object using this library and send it to c# client it succeeds to unpack it because I specific to which object I want to upack it `var serializer = SerializationContext.Default.GetSerializer<Client>(); var client = serializer.Unpack(stream)` I suppose this library should also have something similar?
