### ISSUE TITLE
Possible for c++ bindings?

### ISSUE THREAD

**Issue by Dillybob92** [kawanet/msgpack-lite#35]
I've tested bson, pson, msgpack5 and everything.

This module is the fastest.  It's right next to speeds of JSON and I love it.  I am wondering, if you could even push it for more performance with a native c/c++ binding of it?  

I love it, thanks for all your hard work kawanet.

**Comment by kawanet** [comment]
Thanks. The key factor of the library's speed is less memory copy operations.
It sees Google's FlatBuffers has a similar approach and C/C++ version as well.

https://google.github.io/flatbuffers/

The msgpack-lite started at Jul 25, 2015.
JavaScript version of FlatBuffers looks started [Aug 17, 2015](https://github.com/google/flatbuffers/commits/master/js/flatbuffers.js).
