### ISSUE TITLE
Support part buffer for decode

### ISSUE THREAD

**Issue by KlonD90** [kawanet/msgpack-lite#43]
It's about that works in this way:
```
var b = Buffer.alloc(1000);
msgPackBuffer.copy(b, 100);
var obj = m.decode(b, {from: 100, length: msgPackBuffer.length});
```

My case: https://github.com/KlonD90/node-tarantool-driver. Now work for optimisation and use your implementation. I want less allocation for more speed/less memory usage.

Please help me with improve this. Can i pull request you or do something for this way?

**Comment by kawanet** [comment]
There is a public but undocumented lower-level class `Decoder` as I've mentioned at #31. I guess the code below would work with this class.

```js
var Decoder = require("msgpack-lite").Decoder;
var decoder = new Decoder();
decoder.buffer = msgPackBuffer;
decoder.offset = 100;
var obj = decoder.fetch(); // decode the first element only
```

**Comment by KlonD90** [comment]
@kawanet thank you :) it is very helpful for me.
