### ISSUE TITLE
UTF-8 isn't encoded/decoded correctly

### ISSUE THREAD

**Issue by maciejhirsz** [kawanet/msgpack-lite#46]
```js
msgpack.encode('🐦')
```

- Produces: `[166, 237, 160, 189, 237, 176, 166]`
- Expected: `[164, 240, 159, 144, 166]`

The UTF-16 surrogate pair is incorrectly encoded as two pairs of 3 byte UTF-8 codepoints instead of a single 4 byte codepoint.

It seems intentional, given this comment (`buffer-lite.js:21`):
```
// JavaScript's string uses UTF-16 surrogate pairs for characters other than BMP.
// This encodes string as CESU-8 which never reaches 4 octets per character.
```
I don't see the ability to encode CESU-8 instead of UTF-8 in the msgpack spec though. This will lead to interoperability issues with other msgpack implementations at best, crashing with incorrectly decoded codepoints at worst.

I wrote a plain JavaScript UTF-8 implementation before, will make a PR when I get a moment.

**Comment by maciejhirsz** [comment]
Note: benchmarking things on my own, I found that building strings by simply concatenating to a string via `+=` operator is faster than creating a preallocated array and calling `String.fromCharCode.apply`.

**Comment by kawanet** [comment]
> building strings by simply concatenating to a string via += operator is faster than creating a preallocated array and calling String.fromCharCode.apply.

Really!?!? I was pretty surprised with this!

https://github.com/feross/buffer/blob/master/index.js#L997
Buffer shim is also use the same `String.fromCharCode.apply` technique still. 

I guess that `buffer-lite.js` on the master branch creates two Arrays at least on `toString`. It may cost.  Building/parsing string would give the most impact for decoding/encoding performance. I'd love to see it in depth.

Thanks for the great patch anyway.

**Comment by maciejhirsz** [comment]
Note: the benchmarks I was running for this were on Node 6.3 and Chrome Canary 54, so take it with a big grain of salt, different browsers might vary.

For longer stings (>~128) if your buffer happens to be `Uint8Array`, the absolutely fastest string decoding you can get is by passing a `Uint8Array#subarray` to `TextDecoder#decode` - it's comparable in performance to using `Buffer#toString` in Node.js, and beats `JSON.parse`. The threshold is whatever the cost there is to initialize a new TypedArray, which seems to always be in the range of 100 - 500 ns on my hardware for whatever reason, even when using already allocated `ArrayBuffer`.

**Comment by gordomium** [comment]
Hope it be fixed

**Comment by kawanet** [comment]
0.1.26 published. Thanks!
