### ISSUE TITLE
Publishing latest releases to NPM?

### ISSUE THREAD

**Issue by zbjornson** [kawanet/msgpack-lite#48]
The latest version of this lib in npm is 0.1.20, but it looks like the latest in github is 0.1.25. Are 0.1.21 - 0.1.25 considered unstable or should they be published to npm?

**Comment by kawanet** [comment]
The current version on the github master branch works fine for me. I'm using it on several projects. I'd love to publish it asap but I was pretty busy for those weeks. Wait for a moment, thanks!

**Comment by dbrgn** [comment]
That would be great :)

**Comment by kawanet** [comment]
0.1.26 published
