### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by 20zinnm** [kawanet/msgpack-lite#50]
Would some TypeScript definitions be possible in the near future? If I were more familiar with the project I'd offer.

**Comment by kawanet** [comment]
Pull requests are pretty welcomed.

**Comment by arusakov** [comment]
@kawanet 
I wanna help with typings for TypeScript.
I am right, that browser version does not have streams API?

**Comment by endel** [comment]
Does anyone started this yet?

**Comment by endel** [comment]
Hey everyone,

I just created a pull request for the definitions here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11690

I'd appreciate any feedback if everything is ok there!
Cheers

**Comment by endel** [comment]
Just to let you know that the type definitions are already available here: https://www.npmjs.com/package/@types/msgpack-lite

**Comment by kawanet** [comment]
Thanks @endel,

See also https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13826
