### ISSUE TITLE
Newbie Question: How to unpack a base64 encoded string which encapsulates data

### ISSUE THREAD

**Issue by aprilmateo** [kawanet/msgpack-lite#52]
Hi,

We have a service that packs some data (int, int, boolean) and encodes it (base 64 encoding). It spits out the base64 encoded string. Now I am creating a client side javascript that decodes this string. How do I use it using msgpack-lite? I've read that a multi-level msgpack requires a different handling. Please advise.

Cheers!

**Comment by kawanet** [comment]
Decoding from base64:

``` js
msgpack.decode(Buffer.from('pWhlbGxv', 'base64')) // => hello
```

Encoding to base64:

``` js
msgpack.encode("hello").toString('base64') // => pWhlbGxv
```

**Comment by aprilmateo** [comment]
The base64 encoded string has encapsulated data. I actually have a nodejs script that decodes this, and Im trying to convert it to client side js that will work on most browsers. Here's the nodejs code snippet on how it is upacked:

```
    const strBuffer = new Buffer(base64EncodedString, 'base64');
const unpacker = new msgpack.Unpacker(strBuffer);
const unpackedLong1 = unpacker.unpackInt();
const unpackedLong2 = unpacker.unpackInt();
```

How can I use msgpack-lite to decode like this?

**Comment by kawanet** [comment]
``` js
var msgpack = require("msgpack-lite");
var strBuffer = new Buffer(base64EncodedString, 'base64');
var unpacked = msgpack.decode(strBuffer);
console.warn(unpacked);
```

**Comment by ValentinBossi** [comment]
Hi,

In my Java code i have tested the example code from the official msgpack java repository:
`MessageBufferPacker packer = MessagePack.newDefaultBufferPacker();
packer
                .packInt(1)
                .packString("leo")
                .packArrayHeader(2)
                .packString("xxx-xxxx")
                .packString("yyy-yyyy");
packer.close();`

I can decode the first integer in the browser but all other packages not.
How i can decode the other packages?

Cheers!

**Comment by kawanet** [comment]
Use event mode of the module: 

```js
var msgpack = require("msgpack-lite");

var decoder = msgpack.Decoder();
decoder.on("data", function(data) {
  // you'll receive 1, "leo", 2, "xxx-xxxx" and "yyy-yyyy" in order
});
decoder.on("end", function() {
  // 
});
decoder.decode(buf);
```

**Comment by ValentinBossi** [comment]
soo cool:D thank you very much!
