### ISSUE TITLE
Tag recent releases in GitHub?

### ISSUE THREAD

**Issue by cvermilion** [kawanet/msgpack-lite#57]
It looks like the latest version available from the GitHub [release page](https://github.com/kawanet/msgpack-lite/releases) is 0.1.21. Do you mind adding a release for 0.1.26 (and future releases)? It would be very helpful in packaging this library for use in ClojureScript. Thanks!

**Comment by kawanet** [comment]
Thanks! https://github.com/kawanet/msgpack-lite/releases/tag/0.1.26

**Comment by cvermilion** [comment]
Awesome, thanks!
