### ISSUE TITLE
Registering application specific EXT formats

### ISSUE THREAD

**Issue by kawanet** [kawanet/msgpack-lite#7]
See also: Signature: option parameters and streaming destination #6

At the current version, EXT formats are defined by the module.
It should allow applications to register application specific formats.

**Comment by kawanet** [comment]
Proposal:

(1) Encoder/decoder-wide private codec

```js
var codec = msgpack.createCodec();
codec.setExtDecoder(0x0D).builder(Date);
codec.setExtEncoder(Date).parser(Number);
var obj = {"now": new Date()};
var opt = {codec: codec};
msgpack.encode(obj, opt);
```

(2) application-wide global codec

```js
var codec = msgpack.codec; // global default codec
codec.setExtDecoder(0x0D).builder(Date);
codec.setExtEncoder(Date).parser(Number);
var obj = {"now": new Date()};
msgpack.encode(obj); // no option needed
```

**Comment by kawanet** [comment]
Proposal 2:

```
var codec = msgpack.createExtCodec();
codec.addExtPacker(0x0D, Date, function(date) {
  return msgpack.encode(date - 0);
});
codec.addExtUnpacker(0x0D, function(date) {
  return new Date(msgpack.decode(date));
});
var buf = msgpack.encode(obj, {codec: codec});
var obj = msgpack.decode(buf, {codec: codec});
```

- packer is a filter function which convert an object to a Buffer.
- unpacker is a filter function which convert a Buffer to an object.

**Comment by ubershy** [comment]
Hello. I would really like to use this feature.

**Comment by JoshuaWise** [comment]
This is a feature I really need too. #23 addresses this with a solution similar to `Proposal 2`, but I actually would prefer something like `Proposal 1`, as it allows an application to use multiple codecs, and it keeps simplicity.

Do you think you'll be adding this feature sometimes soon?

**Comment by kawanet** [comment]
> Do you think you'll be adding this feature sometimes soon?

Unfortunately, no. I've started a trial implementation once before but it's not completed in due to my free time shortage at that moment. I mean that PR must be welcomed.

The current version of `lib/ext.js` has a most part of Proposal 3 implementation but not documented and I hope any applications depend on it.

```js
  var preset = new Ext();
  preset.addExtPacker(0x0D, Date, join(Number, encode));
  preset.addExtUnpacker(0x0D, join(decode, unpackClass(Date)));
```

It looks almost a kind of magic, however, `join` function above generates functions something like below:

```js
preset.addExtPacker(0x0D, Date, function(date) {
  return msgpack.encode(date - 0);
});
preset.addExtUnpacker(0x0D, function(date) {
  return new Date(msgpack.decode(date));
});
```

**Comment by JoshuaWise** [comment]
See #24 for an implementation of proposal 3.
